### ISSUE TITLE
compilation issues on multiple vms

### ISSUE THREAD

**Issue by cd-root** [icyguider/Shhhloader#14]
![image](https://user-images.githubusercontent.com/63755392/165171485-c198ea0b-390a-46b1-aadc-9c19b071351a.png)

**Comment by cd-root** [comment]
Ive tried on two VMs on different computers

**Comment by icyguider** [comment]
That's a bit odd; I haven't seen anyone that's gotten this error so far. I did try it in on a few different Linux boxes to see if I could replicate, however everything worked for me as expected.

I tried compiling on:
- Kali in VMware
- Kali in Docker
- Debian 11 Cloud Server

As I said, all worked as expected without issue, so I'm not sure what's causing it to fail on your end. Perhaps you can try a clean Kali/Debian install like I did and see if that works for you. You could also try re-installing mingw-w64 as that's the only dependency and that seems to be what's not working for you.

![alt text](https://i.imgur.com/XeDNoIi.png)
