### ISSUE TITLE
DLL proxy function does not create any exports

### ISSUE THREAD

**Issue by vysecurity** [icyguider/Shhhloader#21]
Tried to run it using the same command line options you gave, but my output DLL has no Exports?

```
ino a.dll | jq .Exports
null
```

**Comment by icyguider** [comment]
Hi again @vysecurity :)

I'm not quite sure why that's happening. The legitimate DLL you are trying to create a wrapper for is in your current directory, correct? 

To try and replicate your issue, I ran the following command to create a DLL wrapper for cscapi.dll:
```
./Shhhloader.py meter.bin -m ModuleStomping -d -p 'C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe' -dp cscapi.dll -l -w -ns
```

I then transferred it over to my Windows machine and checked the exports with dumpbin, which does show that the exports were added successfully:
```
dumpbin /EXPORTS .\a.dll
```
![alttext](https://i.imgur.com/pF88w14.png)

This test was done on a different Linux and Windows box than was seen in my video. My code does not perform much validation or error handling when creating the DLL wrapper (something I plan to update at some point), so it could be that some minor difference in how the def file is being generated is what's causing it to fail for you.

Perhaps try commenting out the lines that delete the stub and def file, regenerate the DLL, and compiling the stub manually. That way you can inspect the .def file to see in anything looks mangled or incorrect. My code was built using [this guide](https://github.com/tothi/dll-hijack-by-proxying) by tothi, so you could also try consulting that to see if you can create a working def file for your target dll without Shhhloader. If that works, then there's definitely some bug in my tool that causes the proxy generation to fail under certain circumstances.

Hopefully this was helpful and we can figure out what's going on.

**Comment by vysecurity** [comment]
Woops accidentally closed.

**Comment by icyguider** [comment]
@vysecurity Would you mind posting the stub.def file here so I can take a closer look at it?

**Comment by vysecurity** [comment]
Better share privately :-)
