### ISSUE TITLE
llvm obfuscator cause error when compiling!

### ISSUE THREAD

**Issue by T1Cr4azy** [icyguider/Shhhloader#26]
### First Thanks for your amazing work!

**The previous version was working fine but after the update it started to go wrong, I compiled the llvm following your installation tutorial!
I tested if it was the llvm binaries to see if there was something wrong but everything was normal compile other .cpp files correctly**
![Shhhloder1](https://user-images.githubusercontent.com/85311985/202543931-0afe2117-5f62-43db-bd5e-d62e268627be.png)

![Shhhloder2](https://user-images.githubusercontent.com/85311985/202543428-41d980bc-f69d-477f-90a5-6a12a0df58c0.png)
I am available to send any data or additional information

**Comment by icyguider** [comment]
If you installed OLLVM using the guide I provided in the README, it will break every time you update clang via apt. To fix it, you must re-copy the OLLVM binaries to your /usr/bin/ folder and re-copy the library files into the new clang directory being used by the system. The screenshot you provided shows which path clang is currently configured at, so simply copy your library files to that location and you should be good to go. There is also no need to recompile OLLVM so long as you still have the build on your PC/VM. 

As I said in the readme, there's definitely better ways to install/use OLLVM, so I'd try to come up with a better solution if it's something you plan on using long term. I did want to leave SOMETHING for the end user to figure out themselves. :stuck_out_tongue_closed_eyes:

I will be closing this as OLLVM installation issues really have nothing to do with this project.

**Comment by T1Cr4azy** [comment]
Thanks for your attention and sorry for my stupidity, I'm new and every problem is a storm for me!

your project is maguinific

Thank you so much!
