### ISSUE TITLE
msfvenom alternatives [question]

### ISSUE THREAD

**Issue by miralayipouya** [icyguider/Shhhloader#4]
Hi @icyguider ! hope you are doing well.
I am re-creating a tool like msfvenom using python, and in the process I am dealing with some problems related to the design complexity of msfvenom.
Do you have any suggestion for me on open-source stuff which would help me achieve such a task?
I have already seen projects such as Veil or OWASP ZSC, but these tools are not active any more.
Cheers!

**Comment by icyguider** [comment]
Hi @miralayipouya. I hope you are doing well too!

Unfortunately, what you are speaking of is definitely outside my area of knowledge. Therefore, I don't think I really know of anything useful that could help you. Perhaps try checking out [venom](https://github.com/r00t-3xp10it/venom.git) or [shellter](https://www.shellterproject.com/download/)? Again, apologies if they aren't very helpful.

Your project does sound interesting though and I'm definitely interested in checking it out once it's completed. Best of luck!
